services:
  - type: web
    name: united-holidays-api
    runtime: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: npm ci --legacy-peer-deps && npm run build
    startCommand: node dist/server.bundle.mjs
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_NAME
        value: united_holidays
      - key: DB_PORT
        value: 3306
